# yaml-language-server: $schema=../../../../tooling/schemas/inventory/resource.schema.json
apiVersion: compliance.example/v1alpha1
kind: InventoryGroup
metadata:
  name: container-runtime-servers
spec:
  parentRefs:
    - name: linux-servers
  selector:
    matchLabels:
      feature-container-runtime: enabled
