apiVersion: compliance.example/v1alpha1
kind: PolicyAssignment
metadata:
  name: administrative-access-objectives
spec:
  targetRef:
    kind: InventoryGroup
    name: administrative-access-scope
  baselineRefs:
    - name: company.administrative-access-objectives
      revision: "1"
