# yaml-language-server: $schema=../../../../tooling/schemas/inventory/resource.schema.json
apiVersion: compliance.example/v1alpha1
kind: InventoryGroup
metadata:
  name: aws-accounts
spec:
  parentRefs:
    - name: cloud-services
  selector:
    matchLabels:
      provider: aws
