# yaml-language-server: $schema=../../../../tooling/schemas/inventory/resource.schema.json
apiVersion: compliance.example/v1alpha1
kind: InventoryGroup
metadata:
  name: managed-macos-development-endpoints
spec:
  selector:
    matchLabels:
      company: alder-forge
      role: managed-development
